server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #服务名大小统一
      routes:
        - id: admin-server_route
          uri: lb://admin-server
          predicates:
            - Path=/admin/**
        - id: test
          uri: https://www.baidu.com/
          predicates:
            - Path=/test
    # 配置限流
    sentinel:
      transport:
        dashboard: sentinel-server:8858
#      datasource:
#        ds1.file:
#          file: classpath:gw-flow.json
#          ruleType: gw_flow
#        ds2.file:
#          file: classpath:gw-api.json
#          ruleType: gw_api_group

shop:
  filter:
    allowPaths: #白名单列表
      - /api/auth/login
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/pay
      #- /api/order
